/* operadores e paravras chaves JavaScript; */

string operators[] = {
"=", /* EQ */
"+", /* ADD */
"-", /* SUB */
"!", /* NOT */
"&", /* AND */
"*", /* MUL */
"/", /* DIV */
"(", /* LPAREN */
")", /* RPAREN */
".", /* DOT */
",", /* COMMA */
"?", /* QUESTION */
"~", /* TILDE */
":", /* COLON */
";", /* SEMICOLON */
"{", /* LBRACE */
"}", /* RBRACE */
"[", /* LBRACK */
"]", /* RBRACK */
"<", /* LESSER */
"|", /* OR */
"^", /* XOR */
"%", /* MOD */
">", /* GREATER */
"==", /* EQEQ */
"+=", /* ADDEQ */
"++", /* INCR */
"-=", /* SUBEQ */
"--", /* DECR */
"!=", /* NOTEQ */
"&=", /* ANDEQ */
"&&", /* LAND */
"|=", /* OREQ */
"||", /* LOR */
"^=", /* XOREQ */
"^^", /* LXOR */
"%=", /* MODEQ */
"/=", /* DIVEQ */
"*=", /* MULEQ */
"<=", /* LESSEREQ */
"<<", /* LSHF */
">=", /* GREATEREQ */
">>", /* RSHF */
"=>", /* FARROW */
"<<=", /* LSHFEQ */
"===", /* EQEQEQ */
"!==", /* NOTEQEQ */
">>=", /* RSHFEQ */
">>>", /* URSHF */
">>>=" /* URSHFEQ */
};


string reserved_words[] = {
"do", /* DO */
"in", /* IN */
"of", /* OF */
"if", /* IF */
"for", /* FOR */
"let", /* LET */
"new", /* NEW */
"try", /* TRY */
"var", /* VAR */
"void", /* VOID */
"with", /* WITH */
"this", /* THIS */
"case", /* CASE */
"else", /* ELSE */
"break", /* BREAK */
"catch", /* CATCH */
"class", /* CLASS */
"const", /* CONST */
"super", /* SUPER */
"throw", /* THROW */
"while", /* WHILE */
"yield", /* YIELD */
"delete", /* DELETE */
"export", /* EXPORT */
"import", /* IMPORT */
"return", /* RETURN */
"switch", /* SWITCH */
"typeof", /* TYPEOF */
"default", /* DEFAULT */
"extends", /* EXTENDS */
"finally", /* FINALLY */
"function", /* FUNCTION */
"continue", /* CONTINUE */
"debugger", /* DEBUGGER */
"instanceof" /* INSTANCEOF */
};
